Update finalize_deployment_preparation.yml

diff --git a/.github/workflows/finalize_deployment_preparation.yml b/.github/workflows/finalize_deployment_preparation.yml
--- a/.github/workflows/finalize_deployment_preparation.yml
+++ b/.github/workflows/finalize_deployment_preparation.yml
@@ -23,7 +23,11 @@ jobs:
       - uses: actions/setup-node@v3
         with:
           node-version: ${{ env.node_version }}
-      - name: Checking for last candidate version
+      - name: Configuring git
+        run: |
+          git config user.name 'GitHub Action'
+          git config user.email '<>'
+      - name: Checking for previous candidate version
         if: ${{ success() }}
         run: |
           cd public
@@ -31,69 +35,81 @@ jobs:
             echo ::error title=${{ env.notification_title }}::"Couldn't find previous candidate version! Either the prepare_release_candidate workflow was never run, or there was an issue while it was running!"
             exit 1
           fi
-      - name: Checking for prepared release with candidate
+      - name: Setting release_version
+        if: ${{ success() }}
+        run: |
+          cd public
+          echo "release_version=$(echo $(npm pkg get ${{ env.last_candidate_version }}) | tr -d '"')" >> $GITHUB_ENV
+      - name: Checking for prepared release and candidate
         if: ${{ success() }}
         id: validation
         run: |
-          echo ::notice title=${{ env.notification_title }}::"Checking for existing prep release and candidate"
           cd public
-          release_version="$(echo $(npm pkg get ${{ env.last_candidate_version }}) | tr -d '"')"
-          git config user.name 'GitHub Action'
-          git config user.email '<>'
           git fetch -q
-          if ! git checkout -f "release/${release_version}" ; then
+          
+          if ! git checkout -f "release/${{ env.release_version }}" ; then
             echo ::error title=${{ env.notification_title }}::"Failed to checkout release branch!"
             exit 1
           fi
-          git pull origin "release/${release_version}"
-          if ! npm --no-git-tag-version version ${release_version} ; then
+          
+          git pull origin "release/${{ env.release_version }}"
+          
+          if ! npm --no-git-tag-version version ${{ env.release_version }} ; then
             echo ::error title=${{ env.notification_title }}::"At least one release candidate must exist before finalizing!"
             exit 1
           fi
-          echo "release_version=$(echo "${release_version}")" >> $GITHUB_OUTPUT
-      - name: Merging release across branches
+      - name: Removing custom npm package fields
         if: ${{ success() }}
         run: |
-          release_version="${{ steps.validation.outputs.release_version }}"
-          echo ::notice title=${{ env.notification_title }}::"Editing 'release/${release_version}' branch to '${{ env.preview_branch }}' branch PR title"
           cd public
-          echo "$(npm pkg get version)"
           npm pkg delete "deployment_workflow"
-          cd ..
+      - name: Creating tag for new release
+        if: ${{ success() }}
+        run: |
           git add .
-          git commit -m "Prepare ${release_version}"
-          git tag "${release_version}"
+          git commit -m "Prepare ${{ env.release_version }}"
+          git tag "${{ env.release_version }}"
           git push origin --tags
-          git push origin "release/${release_version}"
-          if ! gh pr create --title "Release ${release_version}" --base "${{ env.preview_branch }}" --body "" ; then
-              echo ::error title=${{ env.notification_title }}::"Failed to create PR from 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
+      - name: Merging "release" branch into "preview" branch
+        if: ${{ success() }}
+        run: |
+          git push origin "release/${{ env.release_version }}"
+          
+          if ! gh pr create --title "Release ${{ env.release_version }}" --base "${{ env.preview_branch }}" --body "" ; then
+              echo ::error title=${{ env.notification_title }}::"Failed to create PR from 'release/${{ env.release_version }}' branch into '${{ env.preview_branch }}' branch"
               exit 1
           fi
-          echo ::notice title=${{ env.notification_title }}::"Merging 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
-          if ! gh pr merge -m "release/${release_version}" ; then
-            echo ::error title=${{ env.notification_title }}::"Failed to merge 'release/${release_version}' branch into '${{ env.preview_branch }}'"
+          
+          if ! gh pr merge -m "release/${{ env.release_version }}" ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to merge 'release/${{ env.release_version }}' branch into '${{ env.preview_branch }}'"
             exit 1
           fi
-          echo ::notice title=${{ env.notification_title }}::"Creating PR from '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
+      - name: Merging "preview" branch into "main" branch
+        if: ${{ success() }}
+        run: |
           git switch "${{ env.preview_branch }}"
           git pull origin "${{ env.preview_branch }}"
-          if ! gh pr create --title "Release ${release_version}" --base "${{ env.main_branch }}" --body "" ; then
+          
+          if ! gh pr create --title "Release ${{ env.release_version }}" --base "${{ env.main_branch }}" --body "" ; then
             echo ::error title=${{ env.notification_title }}::"Failed to create PR from '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
             exit 1
           fi
-          echo ::notice title=${{ env.notification_title }}::"Merging '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
+          
           if ! gh pr merge -m "${{ env.preview_branch }}" ; then
             echo ::error title=${{ env.notification_title }}::"Failed to merge '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
             exit 1
           fi
-          echo ::notice title=${{ env.notification_title }}::"Creating PR from '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
+      - name: Merging "main" branch into "next" branch
+        if: ${{ success() }}
+        run: |  
           git switch "${{ env.main_branch }}"
           git pull origin "${{ env.main_branch }}"
-          if ! gh pr create --title "Release ${release_version}" --base "${{ env.next_branch }}" --body "" ; then
+          
+          if ! gh pr create --title "Release ${{ env.release_version }}" --base "${{ env.next_branch }}" --body "" ; then
             echo ::error title=${{ env.notification_title }}::"Failed to create PR from '${{ env.main_branch }}' branch to '${{ env.next_branch }}' branch"
             exit 1
           fi
-          echo ::notice title=${{ env.notification_title }}::"Merging '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
+          
           if ! gh pr merge -m "${{ env.main_branch }}" ; then
             echo ::error title=${{ env.notification_title }}::"Failed to merge '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
             exit 1
@@ -101,9 +117,7 @@ jobs:
       - name: Deleting release branch and fast forwarding the others
         if: ${{ success() }}
         run: |
-          release_version="${{ steps.validation.outputs.release_version }}"
-          git push origin --delete "release/${release_version}"
-          echo ::notice title=${{ env.notification_title }}::"Fast forwarding '${{ env.main_branch }}' and '${{ env.preview_branch }}' branches to ensure they aren't 'behind' on commits after merger"
+          git push origin --delete "release/${{ env.release_version }}"
           git pull origin "${{ env.next_branch }}"
           git push origin "${{ env.main_branch }}"
           git switch "${{ env.preview_branch }}"
