Update finalize_deployment_preparation.yml

diff --git a/.github/workflows/finalize_deployment_preparation.yml b/.github/workflows/finalize_deployment_preparation.yml
--- a/.github/workflows/finalize_deployment_preparation.yml
+++ b/.github/workflows/finalize_deployment_preparation.yml
@@ -56,25 +56,35 @@ jobs:
       - name: Merging release across branches
         run: |
           release_version="${{ steps.validation.outputs.release_version }}"
-          echo ::notice title=${{ env.notification_title }}::"Editing 'release' to 'preview' pr title"
+          echo ::notice title=${{ env.notification_title }}::"Editing 'release/${release_version}' branch to '${{ env.preview_branch }}' branch PR title"
           git add .
           git commit -m "Prepare ${release_version}"
           git push origin "release/${release_version}"
           gh pr edit --title "Release ${release_version}"
-          echo ::notice title=${{ env.notification_title }}::"Merging release into preview"
-          gh pr merge -m "release/${release_version}"
-          echo ::notice title=${{ env.notification_title }}::"Creating pr from preview into main"
+          echo ::notice title=${{ env.notification_title }}::"Merging 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
+          if ! gh pr merge -m "release/${release_version}" ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to merge 'release/${release_version}' branch into '${{ env.preview_branch }}'"
+          fi
+          echo ::notice title=${{ env.notification_title }}::"Creating PR from '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
           git switch "${{ env.preview_branch }}"
           git pull origin "${{ env.preview_branch }}"
-          gh pr create --title "Release ${release_version}" --base "${{ env.main_branch }}" --fill
-          echo ::notice title=${{ env.notification_title }}::"Merging preview into main"
-          gh pr merge -m "${{ env.preview_branch }}"
-          echo ::notice title=${{ env.notification_title }}::"Creating pr from main into next"
+          if ! gh pr create --title "Release ${release_version}" --base "${{ env.main_branch }}" --fill ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to create PR from '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
+          fi
+          echo ::notice title=${{ env.notification_title }}::"Merging '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
+          if ! gh pr merge -m "${{ env.preview_branch }}" ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to merge '${{ env.preview_branch }}' branch into '${{ env.main_branch }}' branch"
+          fi
+          echo ::notice title=${{ env.notification_title }}::"Creating PR from '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
           git switch "${{ env.main_branch }}"
           git pull origin "${{ env.main_branch }}"
-          gh pr create --title "Release ${release_version}" --base "${{ env.next_branch }}" --fill
-          echo ::notice title=${{ env.notification_title }}::"Merging main into next"
-          gh pr merge -m "${{ env.main_branch }}"
+          if ! gh pr create --title "Release ${release_version}" --base "${{ env.next_branch }}" --fill ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to create PR from '${{ env.main_branch }}' branch to '${{ env.next_branch }}' branch"
+          fi
+          echo ::notice title=${{ env.notification_title }}::"Merging '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
+          if ! gh pr merge -m "${{ env.main_branch }}" ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to merge '${{ env.main_branch }}' branch into '${{ env.next_branch }}' branch"
+          fi
       - name: Cleaning up branches
         run: |
           release_version="${{ steps.validation.outputs.release_version }}"
