Update finalize_deployment_preparation.yml

diff --git a/.github/workflows/finalize_deployment_preparation.yml b/.github/workflows/finalize_deployment_preparation.yml
--- a/.github/workflows/finalize_deployment_preparation.yml
+++ b/.github/workflows/finalize_deployment_preparation.yml
@@ -62,8 +62,8 @@ jobs:
           git add .
           git commit -m "Prepare ${release_version}"
           git push origin "release/${release_version}"
-          if ! gh pr create --title "Release ${release_version}" --base "${{ env.preview_branch }}" --fill ; then
-            echo ::error title=${{ env.notification_title }}::"Failed to create PR from 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
+          if ! gh pr edit --title "Release ${release_version}" && ! gh pr create --title "Release ${release_version}" --base "${{ env.preview_branch }}" --fill ; then
+            echo ::error title=${{ env.notification_title }}::"Failed to create/edit PR from 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
             exit 1 
           fi
           echo ::notice title=${{ env.notification_title }}::"Merging 'release/${release_version}' branch into '${{ env.preview_branch }}' branch"
